### ISSUE TITLE
DynamoDB update item not working

### ISSUE THREAD

**Issue by fabioz23** [alexa-samples/skill-sample-nodejs-smarthome-switch#11]
Hi, trying this example i see that the dynamodb updateItem (i've tryed also putItem) doesn't work.
The response to the request.send is this:

```
2020-03-13T23:48:43.174Z	27d6c4a5-4927-19ec-7050-361fd4053906	INFO	Response {
  request: Request {
    domain: null,
    service: Service {
      config: [Config],
      isGlobalEndpoint: false,
      endpoint: [Endpoint],
      _events: [Object],
      MONITOR_EVENTS_BUBBLE: [Function: EVENTS_BUBBLE],
      CALL_EVENTS_BUBBLE: [Function: CALL_EVENTS_BUBBLE],
      _clientId: 1
    },
    operation: 'updateItem',
    params: {
      TableName: 'SampleSmartHome',
      Key: [Object],
      AttributeUpdates: [Object],
      ReturnValues: 'UPDATED_NEW'
    },
    httpRequest: HttpRequest {
      method: 'POST',
      path: '/',
      headers: [Object],
      body: '{"TableName":"SampleSmartHome","Key":{"ItemId":{"S":"sample-switch-04"}},"AttributeUpdates":{"powerStateValue":{"Action":"PUT","Value":{"S":"ON"}}},"ReturnValues":"UPDATED_NEW"}',
      endpoint: [Endpoint],
      region: 'eu-west-1',
      _userAgent: 'aws-sdk-nodejs/2.585.0 linux/v12.15.0 exec-env/AWS_Lambda_nodejs12.x',
      stream: [ClientRequest]
    },
    startTime: 2020-03-13T23:48:43.097Z,
    response: [Circular],
    _asm: AcceptorStateMachine { currentState: 'send', states: [Object] },
    _haltHandlersOnError: false,
    _events: {
      validate: [Array],
      afterBuild: [Array],
      restart: [Array],
      sign: [Array],
      validateResponse: [Array],
      send: [Array],
      httpHeaders: [Array],
      httpData: [Array],
      httpDone: [Array],
      retry: [Array],
      afterRetry: [Array],
      build: [Array],
      extractData: [Array],
      extractError: [Array],
      httpError: [Array],
      success: [Array],
      complete: [Array]
    },
    emit: [Function: emit],
    API_CALL_ATTEMPT: [Function: API_CALL_ATTEMPT],
    API_CALL_ATTEMPT_RETRY: [Function: API_CALL_ATTEMPT_RETRY],
    API_CALL: [Function: API_CALL],
    signedAt: 2020-03-13T23:48:43.108Z
  },
  data: null,
  error: null,
  retryCount: 0,
  redirectCount: 0,
  httpResponse: HttpResponse {
    statusCode: undefined,
    headers: {},
    body: undefined,
    streaming: false,
    stream: null,
    _abortCallback: [Function: callNextListener]
  },
  maxRetries: 10,
  maxRedirects: 10
}

```

**Comment by fabioz23** [comment]
running on aws lambda and in docker container (sam build) give the same result.

**Comment by fabioz23** [comment]
i've checked policy, IAM permissions, etc. It seems ok.

Running a putItem via aws CLI (with the same credentials) on terminal it works.

**Comment by xLarry** [comment]
I just came accross the same issue and it turned out that the lambda function ends before the `updateItem()` call is actually complete. I _guess_ this results in aborting the update request.

As a quick fix, I turned the request in [L136](https://github.com/alexa/skill-sample-nodejs-smarthome-switch/blob/eebcd918f3d8407242b9e36821743a2a2ec8b491/lambda/smarthome/index.js#L136) into a promise and waited for it to complete:
```js
let response = await request.promise()
```
Note that you'll need to declare the surrounding function as `async` and also prepend the `await` keyword when calling it in [L93](https://github.com/alexa/skill-sample-nodejs-smarthome-switch/blob/eebcd918f3d8407242b9e36821743a2a2ec8b491/lambda/smarthome/index.js#L93).

**Comment by malcolmcdixon** [comment]
> 
> 
> I just came accross the same issue and it turned out that the lambda function ends before the `updateItem()` call is actually complete. I _guess_ this results in aborting the update request.
> 
> As a quick fix, I turned the request in [L136](https://github.com/alexa/skill-sample-nodejs-smarthome-switch/blob/eebcd918f3d8407242b9e36821743a2a2ec8b491/lambda/smarthome/index.js#L136) into a promise and waited for it to complete:
> 
> ```js
> let response = await request.promise()
> ```
> 
> Note that you'll need to declare the surrounding function as `async` and also prepend the `await` keyword when calling it in [L93](https://github.com/alexa/skill-sample-nodejs-smarthome-switch/blob/eebcd918f3d8407242b9e36821743a2a2ec8b491/lambda/smarthome/index.js#L93).

Thanks for this xLarry that helped. I also found that I needed to add an await before invoking the sendDeviceState function:
    let state_set = await sendDeviceState(

**Comment by Ilyt00** [comment]
Thanks for your help xLarry.
