### ISSUE TITLE
device discovery is not working for me.

### ISSUE THREAD

**Issue by schylabs** [alexa-samples/skill-sample-nodejs-smarthome-switch#15]
After following all the steps found that, device discovery is not working for me.
kindly help.

when i discover devices, i get bellow response.
I couldn't find any new Smart Home devices. If you’ve ‎n't already, please enable the smart home skill for your device from the Alexa App.

**Comment by Aymkdn** [comment]
Go to `./working-smarthome/skill-sample-nodejs-smarthome-switch/lambda/smarthome`, then type:
```
npm install uuid-random
npm uninstall uuid
```

And change https://github.com/alexa/skill-sample-nodejs-smarthome-switch/blob/eebcd918f3d8407242b9e36821743a2a2ec8b491/lambda/smarthome/alexa/skills/smarthome/AlexaResponse.js#L16 to:
```js
let uuid = require('uuid-random');
```

Zip again and reupload again the package, then try the test again.

**Comment by aszk** [comment]
Closing. We updated the code to adapt uuid change.
