### ISSUE TITLE
Alexa don't respone "OK" messages

### ISSUE THREAD

**Issue by thangta** [alexa-samples/skill-sample-nodejs-smarthome-switch#5]
As instruction, After send "alexa, turn on sample switch", Alexa should respond with "OK". But In my sample switch, It just return "<Audio only response>".  I can see respose JSON in the Skill Logs.  

![image](https://user-images.githubusercontent.com/13417944/54097740-0d85fc80-43e4-11e9-95aa-e64911df105c.png)

![image](https://user-images.githubusercontent.com/13417944/54097592-7de04e00-43e3-11e9-9d70-5f5bf660fe1a.png)

**Comment by mikemaas-amazon** [comment]
I would look into the event response and see if there is any additional detail in the response itself. Is the response actually valid with a correct access token? It should resemble the documented response at https://developer.amazon.com/docs/smarthome/state-reporting-for-a-smart-home-skill.html#directive but with your current token.

**Comment by shun-dgut** [comment]
I have encountered a problem that can not be identified by off. How can I analyze the link of the problem and what data can I refer to for analysis
![捕获](https://user-images.githubusercontent.com/31812214/88254651-8390b800-cce8-11ea-8fe2-f2dc9fd40755.PNG)
