### ISSUE TITLE
Test Execution succeeded but no device discovered from Alexa Discover Device

### ISSUE THREAD

**Issue by rajenpal033** [alexa-samples/skill-sample-nodejs-smarthome-switch#6]
I have followed each and every steps instructed here in this repo and when I made a test execution, it was successful, from alexa skill, the account link showed successful as well, but no virtual switch discovered and no error in logs.

**Comment by mikemaas-amazon** [comment]
Are you using your developer Alexa account in the US market? For this sample, the account you use for development should also be associated with the Alexa (https://alexa.amazon.com/) account.

**Comment by ArcaneDiver** [comment]
Hey i wrote the skill for italian, the lambda is in virginia and i`m facing the same problem.
How i can fix it?

**Comment by mikemaas-amazon** [comment]
Can you double-check the CloudWatch logs for the Lambda and verify that the Lambda even gets called when you give a voice command to the switch?

If that turns up empty, my other suggestion is to check your lambda region. For example, if your Marketplace account is in Italy you might want to try building the lambda in eu-west-1 region or one of the new recommended ones: https://developer.amazon.com/en-US/docs/alexa/custom-skills/host-a-custom-skill-as-an-aws-lambda-function.html#allowed-regions

**Comment by rajenpal033** [comment]
Sorry, it was my mistake, I had some setup issues. Thank you all.
